"""Build and run the adaptive coding agent repeatable per-story flow."""

from __future__ import annotations

import argparse
import json
from collections.abc import Callable
from functools import partial
from pathlib import Path

from harness import Flow, PolicyEngine, PolicyRule, Runtime, Step
from harness.trace_viewer import print_trace

from steps import (
    APPLY_CONTRACT,
    CODE_CONTRACT,
    PARITY_CONTRACT,
    PLAN_CONTRACT,
    PROFILE_PATH,
    QUALITY_CONTRACT,
    REVIEW_CONTRACT,
    RUN_TESTS_CONTRACT,
    ApplyOutput,
    ProjectProfile,
    apply_change,
    code,
    parity_check,
    plan,
    quality_gate,
    review,
    run_tests,
)


def build_flow(
    approval_callback: Callable[[str, str], bool] | None = None,
) -> Flow:
    """Assemble plan -> code -> gates -> review -> approved apply."""
    policy_engine = PolicyEngine(
        [PolicyRule("apply_adaptive_code_change", "high", requires_approval=True)],
        approval_callback=approval_callback,
    )

    return Flow(
        [
            Step("plan", plan, contract=PLAN_CONTRACT),
            Step("code", code, contract=CODE_CONTRACT),
            Step("parity_check", parity_check, contract=PARITY_CONTRACT),
            Step("run_tests", run_tests, contract=RUN_TESTS_CONTRACT),
            Step("quality_gate", quality_gate, contract=QUALITY_CONTRACT),
            Step("review", review, contract=REVIEW_CONTRACT),
            Step(
                "apply_change",
                partial(apply_change, policy_engine=policy_engine),
                contract=APPLY_CONTRACT,
            ),
        ]
    )


def load_project_profile(path: Path = PROFILE_PATH) -> ProjectProfile:
    """Load the reusable profile generated by the Phase A init flow."""
    return ProjectProfile.model_validate_json(path.read_text(encoding="utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("story", help="Short developer story to implement.")
    args = parser.parse_args()

    trace_path = Path(__file__).with_name("story_trace.jsonl")
    checkpoint_path = Path(__file__).with_name(".story_checkpoint.json")
    runtime = Runtime(
        trace_path=trace_path,
        checkpoint_path=checkpoint_path,
        max_retries=0,
        retry_delay=0,
        max_jumps=20,
    )
    result = runtime.run(
        build_flow(),
        {
            "project_profile": load_project_profile().model_dump(),
            "story": args.story,
        },
    )

    output = result.model_dump() if isinstance(result, ApplyOutput) else result
    print("Result:", json.dumps(output, indent=2))
    print()
    print_trace(trace_path)


if __name__ == "__main__":
    main()
